version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    build: 
      context: .
    image: site:latest
    networks:
      - traefik-net
    ports:
      - "4000:80"
    restart: always
    volumes:
      - nginx-cache:/var/cache/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=Host(`${HOST_NAME}`) && PathPrefix(`${PATH_PREFIX}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.middlewares=frontend-ratelimit"
      - "traefik.http.middlewares.frontend-ratelimit.ratelimit.average=1000"
      - "traefik.http.middlewares.frontend-ratelimit.ratelimit.period=10s"
      - "traefik.http.middlewares.frontend-ratelimit.ratelimit.burst=500"
networks:
  traefik-net:

volumes:
  nginx-cache:
